name: "Push actions"
on: push
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies from cache
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: poetry-ci-dependencies-${{ hashFiles('**/poetry.lock') }}
      - name: Install
        run: poetry install --with test --no-interaction --no-root
        if: steps.poetry-cache.outputs.cache-hit != 'true'
      - name: Run tests
        run: poetry run pytest tests/
